name: Generate Stats Images

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "5 0 * * *"   # jalan tiap hari jam 00:05 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout repo
    - uses: actions/checkout@v3

    # Setup Python (boleh diganti versi lain kalau perlu)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    # Install dependencies
    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt

    # Generate images
    - name: Generate images
      run: |
        python3 generate_images.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXCLUDED: ${{ secrets.EXCLUDED }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
        EXCLUDE_FORKED_REPOS: true

    # Commit dengan jumlah random 1-6, hanya hari Jumat
    - name: Randomized commits on Friday
      run: |
        DAY=$(date +%u)  # Senin=1 ... Jumat=5 ... Minggu=7
        if [ "$DAY" -eq 5 ]; then
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"

          # Tentukan jumlah commit acak antara 1 sampai 6
          COMMITS=$(shuf -i 1-6 -n 1)
          echo "Akan membuat $COMMITS commit hari ini."

          for i in $(seq 1 $COMMITS); do
            echo "Commit ke-$i dibuat pada $(date)" >> random_log.txt
            git add .
            git commit -m "Update generated files ($i)" || true
            git push
          done
        else
          echo "Hari ini bukan Jumat, skip commit."
        fi
