name: Green Contributions (Friday Random Commits)

on:
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Randomized commits on Friday
      env:
        GITHUB_REPO: ${{ github.repository }}
        GH_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        GIT_USER: ${{ secrets.USERNAME }}
        GIT_EMAIL: ${{ secrets.USER_EMAIL }}
      run: |
        set -e
        
        DAY=$(date +%u)
        echo "Hari angka: $DAY"
        if [ "$DAY" -ne 5 ]; then
          echo "Bukan Jumat — skip commit."
          exit 0
        fi

        git config user.name "$GIT_USER"
        git config user.email "$GIT_EMAIL"

        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${GITHUB_REPO}.git

        COMMITS=$(shuf -i 1-6 -n 1)
        echo "Akan membuat $COMMITS commit."

        for i in $(seq 1 $COMMITS); do
          echo "Commit ke-$i pada $(date -u)" >> random_log.txt
          git add random_log.txt

          git commit -m "Auto commit #$i" || echo "Tidak ada perubahan untuk di-commit"
          git push origin HEAD || echo "Push gagal, cek token/permissions"
          sleep 1
        done

        echo "Selesai membuat $COMMITS commit."
